@baseUrl = http://localhost:3000/api
@demoKey = cmmsrgcrj0002els7mqxxzc4b

@tripId = cmn4dgdn0000fpqs7v8viu513

@expenseId = cmn4dhwyz000jpqs7ghuxi44c

### Trip 생성
POST {{baseUrl}}/demo/{{demoKey}}/trips
Content-Type: application/json

{
  "title": "유럽 여행"
}

### Trip 조회
GET {{baseUrl}}/demo/{{demoKey}}/trips

### Participant 생성
POST {{baseUrl}}/demo/{{demoKey}}/trips/{{tripId}}/participants
Content-Type: application/json

{
  "name": "루이"
}

### Participant 조회
GET {{baseUrl}}/demo/{{demoKey}}/trips/{{tripId}}/participants

### Expense 생성
POST {{baseUrl}}/demo/{{demoKey}}/trips/{{tripId}}/expenses
Content-Type: application/json

{
  "title": "1일차 점심",
  "amount": 50000,
  "paidById": "cmmka3cxs0005kbs755s6e9en",
  "splits": [
    {
      "participantId": "cmmka3cxs0005kbs755s6e9en",
      "shareAmount": 50000
    }
  ]
}

### Expense 조회
GET {{baseUrl}}/demo/{{demoKey}}/trips/{{tripId}}/expenses/{{expenseId}}


### status 업데이트
PATCH {{baseUrl}}/demo/{{demoKey}}/trips/{{tripId}}
Content-Type: application/json

{
  "status": "SETTLED"
}

### settlement 조회
GET {{baseUrl}}/demo/{{demoKey}}/trips/{{tripId}}/settlement

